### ISSUE TITLE
can not run calibration.ipynb

### ISSUE THREAD

**Issue by ChunchaoPeter** [hughsalimbeni/bayesian_benchmarks#11]
Hi Hugh,

Thanks for the bayesian_benchmarks. I am new to this area. I really like your work. 
I have run the calibration.ipynb. However, it does not work for me. 
Below is the error.  Could you please help me figure it out?
Thanks in advance.

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-10-604e42cf88f7> in <module>
      9 from database_utils import Database
     10 
---> 11 from data import ALL_CLASSIFICATION_DATATSETS
     12 
     13 classification_datasets = list(ALL_CLASSIFICATION_DATATSETS.keys())

ImportError: cannot import name 'ALL_CLASSIFICATION_DATATSETS' from 'data' (../data.py)

**Comment by hughsalimbeni** [comment]
Thanks for pointing this out. The notebook was a bit out of date. I've updated, and also added a few lines so that the experiments automatically run if the results aren't there already. I also commented out some of the more expensive models so that the whole thing runs faster if running from scratch. Let me know if it works for you.

**Comment by ChunchaoPeter** [comment]
Thanks for your help. It works for me. :)
Thanks a lot.

**Comment by hughsalimbeni** [comment]
Great thanks!
